## Necessary Imports

In [1]:
import matplotlib.pyplot as plt

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

## About Android Traffic Dataset

Public Source - Kaggle:
https://www.kaggle.com/datasets/xwolf12/network-traffic-android-malware

Paper:
Cao, D., Wang, S., Li, Q., Cheny, Z., Yan, Q., Peng, L., & Yang, B. (2016, August). DroidCollector: A High Performance Framework for High Quality Android Traffic Collection. In Trustcom/BigDataSE/I SPA, 2016 IEEE (pp. 1753-1758). IEEE

## Load Data from CSV File

In [3]:
# Read the CSV file with the correct delimiter
df = pd.read_csv('android_traffic.csv', sep=';')

# Display the first few rows of the DataFrame
df.head()

,name,tcp_packets,dist_port_tcp,external_ips,vulume_bytes,udp_packets,tcp_urg_packet,source_app_packets,remote_app_packets,source_app_bytes,remote_app_bytes,duracion,avg_local_pkt_rate,avg_remote_pkt_rate,source_app_packets.1,dns_query_times,type
0,AntiVirus,36,6,3,3911,0,0,39,33,5100,4140,NaN,NaN,NaN,39,3,benign
1,AntiVirus,117,0,9,23514,0,0,128,107,26248,24358,NaN,NaN,NaN,128,11,benign
2,AntiVirus,196,0,6,24151,0,0,205,214,163887,24867,NaN,NaN,NaN,205,9,benign
3,AntiVirus,6,0,1,889,0,0,7,6,819,975,NaN,NaN,NaN,7,1,benign
4,AntiVirus,6,0,1,882,0,0,7,6,819,968,NaN,NaN,NaN,7,1,benign

In [4]:
df.tail()

,name,tcp_packets,dist_port_tcp,external_ips,vulume_bytes,udp_packets,tcp_urg_packet,source_app_packets,remote_app_packets,source_app_bytes,remote_app_bytes,duracion,avg_local_pkt_rate,avg_remote_pkt_rate,source_app_packets.1,dns_query_times,type
7840,Zsone,0,0,0,0,0,0,2,2,257,143,NaN,NaN,NaN,2,2,malicious
7841,Zsone,4,4,1,296,0,0,5,1,86,382,NaN,NaN,NaN,5,1,malicious
7842,Zsone,0,0,0,0,0,0,2,2,257,143,NaN,NaN,NaN,2,2,malicious
7843,Zsone,0,0,0,0,0,0,2,2,257,143,NaN,NaN,NaN,2,2,malicious
7844,Zsone,0,0,0,0,0,0,2,2,257,143,NaN,NaN,NaN,2,2,malicious

In [5]:
df.size

133365

In [6]:
df.shape

(7845, 17)

In [7]:
df.count()

name                    7845
tcp_packets             7845
dist_port_tcp           7845
external_ips            7845
vulume_bytes            7845
udp_packets             7845
tcp_urg_packet          7845
source_app_packets      7845
remote_app_packets      7845
source_app_bytes        7845
remote_app_bytes        7845
duracion                   0
avg_local_pkt_rate         0
avg_remote_pkt_rate        0
source_app_packets.1    7845
dns_query_times         7845
type                    7845
dtype: int64

In [8]:
df.columns

Index(['name', 'tcp_packets', 'dist_port_tcp', 'external_ips', 'vulume_bytes',
       'udp_packets', 'tcp_urg_packet', 'source_app_packets',
       'remote_app_packets', 'source_app_bytes', 'remote_app_bytes',
       'duracion', 'avg_local_pkt_rate', 'avg_remote_pkt_rate',
       'source_app_packets.1', 'dns_query_times', 'type'],
      dtype='object')

In [9]:
df['type'].value_counts()

type
benign       4704
malicious    3141
Name: count, dtype: int64

In [10]:
from sklearn.preprocessing import LabelEncoder
lb = LabelEncoder()
df['type']= lb.fit_transform(df['type'])
df

,name,tcp_packets,dist_port_tcp,external_ips,vulume_bytes,udp_packets,tcp_urg_packet,source_app_packets,remote_app_packets,source_app_bytes,remote_app_bytes,duracion,avg_local_pkt_rate,avg_remote_pkt_rate,source_app_packets.1,dns_query_times,type
0,AntiVirus,36,6,3,3911,0,0,39,33,5100,4140,NaN,NaN,NaN,39,3,0
1,AntiVirus,117,0,9,23514,0,0,128,107,26248,24358,NaN,NaN,NaN,128,11,0
2,AntiVirus,196,0,6,24151,0,0,205,214,163887,24867,NaN,NaN,NaN,205,9,0
3,AntiVirus,6,0,1,889,0,0,7,6,819,975,NaN,NaN,NaN,7,1,0
4,AntiVirus,6,0,1,882,0,0,7,6,819,968,NaN,NaN,NaN,7,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7840,Zsone,0,0,0,0,0,0,2,2,257,143,NaN,NaN,NaN,2,2,1
7841,Zsone,4,4,1,296,0,0,5,1,86,382,NaN,NaN,NaN,5,1,1
7842,Zsone,0,0,0,0,0,0,2,2,257,143,NaN,NaN,NaN,2,2,1
7843,Zsone,0,0,0,0,0,0,2,2,257,143,NaN,NaN,NaN,2,2,1
7844,Zsone,0,0,0,0,0,0,2,2,257,143,NaN,NaN,NaN,2,2,1

In [11]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
tcp_packets,7845.0,147.578713,7.779201e+02,0.0,6.0,25.0,93.0,37143.0
dist_port_tcp,7845.0,7.738177,5.165422e+01,0.0,0.0,0.0,0.0,2167.0
external_ips,7845.0,2.748502,2.923005e+00,0.0,1.0,2.0,4.0,43.0
vulume_bytes,7845.0,16543.752199,8.225650e+04,0.0,888.0,3509.0,12189.0,4226790.0
udp_packets,7845.0,0.056724,1.394046e+00,0.0,0.0,0.0,0.0,65.0
tcp_urg_packet,7845.0,0.000255,1.596581e-02,0.0,0.0,0.0,0.0,1.0
source_app_packets,7845.0,152.911918,7.790346e+02,1.0,7.0,30.0,98.0,37150.0
remote_app_packets,7845.0,194.706310,1.068113e+03,0.0,7.0,24.0,92.0,45928.0
source_app_bytes,7845.0,202496.721224,1.401076e+06,0.0,934.0,4090.0,26244.0,68235164.0
remote_app_bytes,7845.0,16922.603952,8.238182e+04,69.0,1046.0,3803.0,12610.0,4227323.0
duracion,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
avg_local_pkt_rate,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
avg_remote_pkt_rate,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN
source_app_packets.1,7845.0,152.911918,7.790346e+02,1.0,7.0,30.0,98.0,37150.0
dns_query_times,7845.0,4.898917,1.890048e+01,0.0,1.0,3.0,5.0,913.0
type,7845.0,0.400382,4.900071e-01,0.0,0.0,0.0,1.0,1.0

## Distribution of the Classes

In [12]:
# Distribution of the classes
class_distribution = df['type'].value_counts()
print(class_distribution)

type
0    4704
1    3141
Name: count, dtype: int64

## Selection of unwanted columns

In [13]:
# Selection of unwanted columns
unwanted_columns = ['duracion', 'avg_local_pkt_rate', 'avg_remote_pkt_rate', 'source_app_packets.1']
df = df.drop(unwanted_columns, axis=1)

## Remove unwanted columns

In [14]:
# Check if columns exist before dropping
columns_to_drop = [col for col in unwanted_columns if col in df.columns]

In [15]:
# Drop unwanted columns
df = df.drop(columns_to_drop, axis=1)

## Divide the data as Train/Test dataset

In [16]:
from sklearn.model_selection import train_test_split

# Features (X) and target variable (y)
X = df.drop('type', axis=1)
y = df['type']

In [17]:
# Split the data into train and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [18]:
# Display the shapes of the train and test sets
print("Train set shape:", X_train.shape, y_train.shape)
print("Test set shape:", X_test.shape, y_test.shape)

Train set shape: (6276, 12) (6276,)
Test set shape: (1569, 12) (1569,)

## Modeling (SVM with Scikit-learn)

In [19]:
# Get common columns in both sets
common_columns = X_train.columns.intersection(X_test.columns)

# Keep only the common columns in both sets
X_train = X_train[common_columns]
X_test = X_test[common_columns]

In [20]:
from sklearn.preprocessing import LabelEncoder

# Assuming categorical columns are stored in cat_columns
cat_columns = X_train.select_dtypes(include=['object']).columns

# Combine the training and test sets for label encoding
combined_data = pd.concat([X_train, X_test], axis=0)

# Apply LabelEncoder to categorical columns on the combined data
label_encoder = LabelEncoder()
for col in cat_columns:
    combined_data[col] = label_encoder.fit_transform(combined_data[col])

# Split the combined data back into training and test sets
X_train = combined_data.iloc[:X_train.shape[0], :]
X_test = combined_data.iloc[X_train.shape[0]:, :]

In [21]:
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# Initialize the SVM model
# Initialize the SVM model
svm_model = SVC()

# Fit the model on the training data
svm_model.fit(X_train, y_train)

# Make predictions on the test data
y_pred = svm_model.predict(X_test)

# Evaluate the model
accuracy = accuracy_score(y_test, y_pred)
conf_matrix = confusion_matrix(y_test, y_pred)
class_report = classification_report(y_test, y_pred)

print(f"Accuracy: {accuracy}")
print(f"Confusion Matrix:\n{conf_matrix}")
print(f"Classification Report:\n{class_report}")

Accuracy: 0.6022944550669216
Confusion Matrix:
[[937   1]
 [623   8]]
Classification Report:
              precision    recall  f1-score   support

           0       0.60      1.00      0.75       938
           1       0.89      0.01      0.03       631

    accuracy                           0.60      1569
   macro avg       0.74      0.51      0.39      1569
weighted avg       0.72      0.60      0.46      1569